### ISSUE TITLE
Unexpected NPE

### ISSUE THREAD

**Issue by AresM** [QuadFlask/colorpicker#13]
First run 0.0.7. NPE for the second time after invoke dialog.

E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.calmean.app.controler, PID: 29779
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Canvas.drawColor(int, android.graphics.PorterDuff$Mode)' on a null object reference
            at com.flask.colorpicker.slider.AbsCustomSlider.onDraw(AbsCustomSlider.java:62)
            at android.view.View.draw(View.java:15231)
            at android.view.View.updateDisplayListIfDirty(View.java:14167)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.View.draw(View.java:14959)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.draw(View.java:15234)
            at android.view.View.updateDisplayListIfDirty(View.java:14167)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.View.draw(View.java:14959)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14162)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.View.draw(View.java:14959)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14162)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.View.draw(View.java:14959)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.draw(View.java:15234)
            at android.view.View.updateDisplayListIfDirty(View.java:14167)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.View.draw(View.java:14959)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14162)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.View.draw(View.java:14959)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14162)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.View.draw(View.java:14959)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.draw(View.java:15234)
            at android.widget.FrameLayout.draw(FrameLayout.java:598)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2650)
            at android.view.View.updateDisplayListIfDirty(View.java:14167)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
            at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
            at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2530)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2352)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1982)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:6

**Comment by QuadFlask** [comment]
Hmm.... strange.. but I change some code to avoid NPE, but I'm not user because I can't recurrence this issue. I will release new version which named 0.0.8. please test this aar.
