### ISSUE TITLE
Duplicate file

### ISSUE THREAD

**Issue by uname** [QuadFlask/colorpicker#31]
Error:Execution failed for task ':app:processDebugResources'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\Develop\Android\sdk\build-tools\22.0.1\aapt.exe'' finished with non-zero exit value 1
> D:\CodeProj\github\HiLamp\app\Android\app\build\intermediates\res\debug\drawable-hdpi\met_ic_clear.png: Original is here. The version qualifier may be implied.
> D:\CodeProj\github\HiLamp\app\Android\app\build\intermediates\res\debug\drawable-hdpi-v4\met_ic_clear.png: error: Duplicate file.

**Comment by QuadFlask** [comment]
I remove hte MaterialEditText(met) dependency, so have a try

**Comment by uname** [comment]
Thanks QuadFlask!
But another problem comes to me :(
The crash stack:
 java.lang.NullPointerException
            at com.flask.colorpicker.ColorPickerView.findNearestByPosition(ColorPickerView.java:253)
            at com.flask.colorpicker.ColorPickerView.onTouchEvent(ColorPickerView.java:204)
            at android.view.View.dispatchTouchEvent(View.java:7706)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2068)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1515)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2458)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2016)
            at android.view.View.dispatchPointerEvent(View.java:7886)
            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3947)
            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3826)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3442)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3411)
            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3518)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3419)
            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3575)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3442)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3411)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3419)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5532)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5512)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5483)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5612)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java:138)
            at android.os.Looper.loop(Looper.java:123)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by uname** [comment]
Add another tow question:
1. If I connect ColorPickerView to LightnessSlider, how can I get the color when I change the lightness by slide the LightnessSlider?
My code is like this now:
        mColorPicker.addOnColorSelectedListener(new OnColorSelectedListener() {
            @Override
            public void onColorSelected(int color) {
                byte[] packetBuf = PacketHelper.encodePacket((byte)1, new SetLightReq((byte) 255, color));
                LogUtil.d(TAG, "------------> " + StringUtil.bytesToHexString(packetBuf));
            }
        });
However, when I slide the LightnessSlider, onColorSelected was not called:(
AND, I did not found any LightnessSlider's listener which can provide this function:(
1. I use the ColorPickerView(Issue #30 ), But the view will not show immediate unless I call setColor or something else

waiting your response && best wishes!

**Comment by QuadFlask** [comment]
@uname NPE was occur by `renderer == null`. I think you create by `ColorPickerView(Context context)` so that renderer is null(or, renderer was not set)
And you can't get lightness by colorPicker's event listener. If you want this behavior, I will implement this or you can PR and I will merge.

**Comment by uname** [comment]
@QuadFlask  Thanks!
I'm making a Lamp with BLE and your colorPicker is part of my Android app.
I want to have easy way to control the lamp's brightness, so the feature of "get lightness by colorPicker's event listener" is necessary as you mentioned.
I will try to implement it, but if you have time to come it true, I'll will be appreciative:)

**Comment by QuadFlask** [comment]
I implemented that feature. check out that. you can listen from Alpha/LightnessSlider by registering listener `OnValueChangedListener`
the value will [0, 1].

**Comment by uname** [comment]
Thanks , I will try :)
It is my time to sleep, zzzz~~
best wishes
