### ISSUE TITLE
NullPointerException in findNearestByColor

### ISSUE THREAD

**Issue by riddhishah1989** [QuadFlask/colorpicker#48]
I have integrate color picker in Fragment and it is showing me this error everytime. I already done **ActivityObject.onWindowFocusChanged(true);** 
How Can I use this view with fragment.?

**Comment by tobiasschuerg** [comment]
same for me

**Comment by tobiasschuerg** [comment]
Fixed it. As long as the pr is not accepted you may use this version from jitpack:

`
dependencies {  
            compile 'com.github.tobiasschuerg:colorpicker:1.0.12'  
    }
`

https://jitpack.io/#tobiasschuerg/colorpicker/1.0.12

**Comment by QuadFlask** [comment]
version 0.0.11 is released. could you test it?

**Comment by tobiasschuerg** [comment]
I'm going to do so ...

**Comment by hamed-ta** [comment]
I have same issue when I use API 16 and below 
I tested latest version (0.0.12)

how I can solve the problem ?

**Comment by hamed-ta** [comment]
it doesn't work yet on version 0.0.12

**Comment by hamed-ta** [comment]
W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xa6650228)
E/AndroidRuntime: FATAL EXCEPTION: main
                  java.lang.NullPointerException
                      at com.flask.colorpicker.ColorPickerView.setLightness(ColorPickerView.java:367)
                      at com.flask.colorpicker.slider.LightnessSlider.onValueChanged(LightnessSlider.java:52)
                      at com.flask.colorpicker.slider.AbsCustomSlider.onTouchEvent(AbsCustomSlider.java:119)
                      at android.view.View.dispatchTouchEvent(View.java:7127)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1877)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1877)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1877)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1877)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1877)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1877)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1877)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1877)
                      at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1925)
                      at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1379)
                      at android.app.Activity.dispatchTouchEvent(Activity.java:2396)
                      at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:67)
                      at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1873)
                      at android.view.View.dispatchPointerEvent(View.java:7307)
                      at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3174)
                      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3119)
                      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4155)
                      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4134)
                      at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4226)
                      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
                      at android.os.MessageQueue.nativePollOnce(Native Method)
                      at android.os.MessageQueue.next(MessageQueue.java:125)
                      at android.os.Looper.loop(Looper.java:124)
                      at android.app.ActivityThread.main(ActivityThread.java:4745)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:511)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                      at dalvik.system.NativeStart.main(Native Method)
