### ISSUE TITLE
Cant load in FRAGMENT

### ISSUE THREAD

**Issue by moosabaloch** [QuadFlask/colorpicker#52]
When i put this widget in in a fragment then the fragment view was created successfully every time but with a blank colorflask view and when i click on the area of colorflask the exceptions raised mention  below 

`FATAL EXCEPTION: main
                                                                           Process: com.sultanandknight.talpa, PID: 20677
                                                                           java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
                                                                               at com.flask.colorpicker.ColorPickerView.findNearestByPosition(ColorPickerView.java:257)
                                                                               at com.flask.colorpicker.ColorPickerView.onTouchEvent(ColorPickerView.java:206)
                                                                               at android.view.View.dispatchTouchEvent(View.java:8476)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                               at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369)
                                                                               at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
                                                                               at android.app.Activity.dispatchTouchEvent(Activity.java:2752)
                                                                               at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                               at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2330)
                                                                               at android.view.View.dispatchPointerEvent(View.java:8671)
                                                                               at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4193)
                                                                               at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4059)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3604)
                                                                               at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3657)
                                                                               at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3623)
                                                                               at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3740)
                                                                               at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3631)
                                                                               at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3797)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3604)
                                                                               at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3657)
                                                                               at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3623)
                                                                               at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3631)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3604)
                                                                               at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5912)
                                                                               at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5851)
                                                                               at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5822)
                                                                               at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6002)
                                                                               at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
                                                                               at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                               at android.os.MessageQueue.next(MessageQueue.java:143)
                                                                               at android.os.Looper.loop(Looper.java:122)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
`

**Comment by QuadFlask** [comment]
This issue like #32.
could you test 0.0.11 version?

**Comment by hamed-ta** [comment]
I tested the latest version 0.0.12 it doesn't work with API 16 at all , it doesn't appear you can see here 

http://alphabit.ir/oth/screenshot.png

how I can solve the problem ?

**Comment by hamed-ta** [comment]
ok this is full error 

W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xa6650228)
E/AndroidRuntime: FATAL EXCEPTION: main
                  java.lang.NullPointerException
                      at com.flask.colorpicker.ColorPickerView.setLightness(ColorPickerView.java:367)
                      at com.flask.colorpicker.slider.LightnessSlider.onValueChanged(LightnessSlider.java:52)
                      at com.flask.colorpicker.slider.AbsCustomSlider.onTouchEvent(AbsCustomSlider.java:119)
                      at android.view.View.dispatchTouchEvent(View.java:7127)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1877)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1877)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1877)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1877)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1877)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1877)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1877)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1877)
                      at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1925)
                      at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1379)
                      at android.app.Activity.dispatchTouchEvent(Activity.java:2396)
                      at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:67)
                      at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1873)
                      at android.view.View.dispatchPointerEvent(View.java:7307)
                      at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3174)
                      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3119)
                      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4155)
                      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4134)
                      at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4226)
                      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
                      at android.os.MessageQueue.nativePollOnce(Native Method)
                      at android.os.MessageQueue.next(MessageQueue.java:125)
                      at android.os.Looper.loop(Looper.java:124)
                      at android.app.ActivityThread.main(ActivityThread.java:4745)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:511)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                      at dalvik.system.NativeStart.main(Native Method)
