### ISSUE TITLE
Cannot access dialog in a viewpager fragment

### ISSUE THREAD

**Issue by mihirkabani** [QuadFlask/colorpicker#85]
I am trying to access the dialog through a fragment in the ViewPager and attached below is the error that I am facing

06-29 19:49:02.840 6989-6989/[app_name] E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: [app_name], PID: 6989
                                                               java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                   at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:359)
                                                                   at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:328)
                                                                   at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:289)
                                                                   at android.support.v7.app.AppCompatDialog.setContentView(AppCompatDialog.java:83)
                                                                   at android.support.v7.app.AlertController.installContent(AlertController.java:225)
                                                                   at android.support.v7.app.AlertDialog.onCreate(AlertDialog.java:257)
                                                                   at android.app.Dialog.dispatchOnCreate(Dialog.java:394)
                                                                   at android.app.Dialog.show(Dialog.java:295)
                                                                   at [app_name].Fragments.example_fragment$1.onClick(example_fragment.java:81)
                                                                   at android.view.View.performClick(View.java:5201)
                                                                   at android.view.View$PerformClick.run(View.java:21163)
                                                                   at android.os.Handler.handleCallback(Handler.java:746)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by SeaRoth** [comment]
Did you ever figure this out?

**Comment by SeaRoth** [comment]
I fixed it by "using as widget" because I'm using android:theme="@android:style/Theme.Holo.Light.DarkActionBar"

which isn't Theme.AppCompat
