### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by GooSync** [QuadFlask/colorpicker#93]
library version - 0.0.13

From devices:
TECNO 40%
Infinix 20%
Motorola 20%
Samsung 20%

with android version:
7 - 80%
5 - 20%

`Fatal Exception: java.lang.IllegalArgumentException: width and height must be > 0
       at android.graphics.Bitmap.createBitmap(Bitmap.java:903)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:882)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:849)
       at com.flask.colorpicker.slider.AbsCustomSlider.createBitmaps(Unknown Source)
       at com.flask.colorpicker.slider.AbsCustomSlider.updateBar(Unknown Source)
       at com.flask.colorpicker.slider.AbsCustomSlider.onSizeChanged(Unknown Source)
       at android.view.View.sizeChange(View.java:17656)
       at android.view.View.setFrame(View.java:17618)
       at android.view.View.layout(View.java:17535)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
       at android.view.View.layout(View.java:17538)
       at android.view.ViewGroup.layout(ViewGroup.java:5616)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17538)
       at android.view.ViewGroup.layout(ViewGroup.java:5616)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17538)
       at android.view.ViewGroup.layout(ViewGroup.java:5616)
       at android.support.v7.widget.AlertDialogLayout.setChildFrame(Unknown Source)
       at android.support.v7.widget.AlertDialogLayout.onLayout(Unknown Source)
       at android.view.View.layout(View.java:17538)
       at android.view.ViewGroup.layout(ViewGroup.java:5616)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17538)
       at android.view.ViewGroup.layout(ViewGroup.java:5616)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17538)
       at android.view.ViewGroup.layout(ViewGroup.java:5616)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17538)
       at android.view.ViewGroup.layout(ViewGroup.java:5616)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
       at android.view.View.layout(View.java:17538)
       at android.view.ViewGroup.layout(ViewGroup.java:5616)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:724)
       at android.view.View.layout(View.java:17538)
       at android.view.ViewGroup.layout(ViewGroup.java:5616)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2354)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2081)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1258)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6348)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
       at android.view.Choreographer.doCallbacks(Choreographer.java:683)
       at android.view.Choreographer.doFrame(Choreographer.java:619)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)`

**Comment by root-ansh** [comment]
+1 . having the same issue
